# Configuration file for https://circleci.com/
# Inspiration from https://github.com/DevProgress/onboarding/wiki/Using-Circle-CI-with-Github-Pages-for-Continuous-Delivery

version: 2

jobs:
  build:
    docker:
      # Use a Python image from https://hub.docker.com/r/circleci/python/tags/
      - image: circleci/python:3.6

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}
      - run:
          name: Install sphinx dependency
          command: |
            python3 -m venv ~/sphinx-venv
            . ~/sphinx-venv/bin/activate
            pip install sphinx
      - save_cache:
          key: deps-{{ .Branch }}
          paths:
            - ~/sphinx-venv

      - run: make all SPHINXBUILD=~/sphinx-venv/bin/sphinx-build
      - store_artifacts:
          path: _build/html
          destination: build

      - run: make clean
      - run:
          name: Create a git repository in _build/html
          command: |
            mkdir -p _build/html
            git -C _build/html init
      - run:
          name: Configure the user and email which is used with environment variables
          command: |
            git config --global user.email "$GH_EMAIL"
            git config --global user.name "$GH_NAME"
      - run:
          name: Check out gh-pages in _build/html
          command: |
            git -C _build/html remote add --fetch origin "$(git config remote.origin.url)"
            if git -C _build/html rev-parse --verify origin/gh-pages ; then
              git -C _build/html checkout gh-pages &&
              git -C _build/html rm -rf . ;
            else
              git -C _build/html checkout --orphan gh-pages ;
            fi
      - run:
          name: Build Github pages with Sphinx and disable Jekyll engine
          command: |
            make html SPHINXBUILD=~/sphinx-venv/bin/sphinx-build
            touch _build/html/.nojekyll
      - run:
          # Use [ci skip] to prevent Circle-CI from testing this new commit
          name: Commit
          command: |
            git -C _build/html add -A
            git -C _build/html commit --allow-empty -m "Sphinx build of $CIRCLE_SHA1 [ci skip]"
            git -C _build/html format-patch -n1 --stdout > _build/gh-pages.patch
      - store_artifacts:
          path: _build/gh-pages.patch
          destination: gh-pages.patch

      - add_ssh_keys:
          fingerprints:
            - "18:d0:b9:4b:92:29:12:df:1b:69:9e:bd:cd:af:30:9d"
      - deploy:
          name: Deploy gh-pages to Github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git -C _build/html push --quiet origin gh-pages
            fi
